-- Recria a tabela registrations
DROP TABLE IF EXISTS registrations;

CREATE TABLE registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullName" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "age" INTEGER NOT NULL,
  "neighborhood" TEXT NOT NULL,
  "canSew" TEXT NOT NULL,
  "reason" TEXT,
  "timestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW()
); 